// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoJK8mwjWznFxVBJ2JX4O0BzSE8jTlobQ',
    appId: '1:419631692001:web:1ab06588b5694c07cbdfa0',
    messagingSenderId: '419631692001',
    projectId: 'redittclone-1efae',
    authDomain: 'redittclone-1efae.firebaseapp.com',
    storageBucket: 'redittclone-1efae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARomQrrc0PbsOcCHd_lMbnjYvqXV6iA3A',
    appId: '1:419631692001:android:baf241876fdf637ecbdfa0',
    messagingSenderId: '419631692001',
    projectId: 'redittclone-1efae',
    storageBucket: 'redittclone-1efae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1g4Vso9imcamWEkAwCuTBzADuICvIsOw',
    appId: '1:419631692001:ios:10700aa2b4a3e87acbdfa0',
    messagingSenderId: '419631692001',
    projectId: 'redittclone-1efae',
    storageBucket: 'redittclone-1efae.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );
}
